xfinance:
        accounts-config: accounts.yaml
        main-account-number: 81072106
        accumulated-bank-statements-file: $SYNCED/finances/handelsbanken/handelsbanken-full.csv
        bank-statement-template: $DOWNLOADS/Transaction*.csv
        budgeting-classes-file: budgetting-classes.yaml
        configdir: ~/open-projects/github.com/hillwithsmallfields/qs/conf
        conversions-config: conversions.csv
        conversions-dir: $SYNCED/finances
        finances-completions: $SYNCED/var/finances-completions.el
        for-categorization: $SYNCED/finances/for-categorization.csv
        main-account-file: $SYNCED/finances/finances.csv
        merge-results-dir: $SCRATCH/auto-merge-results
        merge-results-file: newly-merged.csv
        thresholds-file: budgetting-thresholds.yaml
        main-current-account: Handelsbanken current account
        main-savings-account: Handelsbanken savings
        account-balances: $SYNCED/finances/account-balances.csv
inventory:
        books-file: $SYNCED/org/books.csv
        inventory-file: $SYNCED/org/inventory.csv
        project-parts-file: $SYNCED/org/project-parts.csv
        stock-file: $SYNCED/org/stock.csv
        storage-file: $SYNCED/org/storage.csv
physical:
        running-filename: $SYNCED/health/garmin-running.csv
        cycling-filename: $SYNCED/health/garmin-cycling.csv
        garmin-incoming-pattern: $DOWNLOADS/Activities*.csv
        garmin-manual-fetching-page: https://connect.garmin.com/modern/activities
        mfp-filename: $SYNCED/health/mfp-accum.csv
        omron-filename: $SYNCED/health/blood-pressure.csv
        omron-incoming-pattern: $DOWNLOADS/BloodPressure_*.csv
        oura-filename: $SYNCED/health/sleep.csv
        physical-filename: $SYNCED/health/physical.csv
        weight-filename: $SYNCED/health/weight.csv
        temperature-file: $SYNCED/health/temperature.csv
dashboard:
        views: $SYNCED/var/views.json
        parcels:  $SYNCED/var/parcels-expected.json
start-page:
        start-page-generator: make_link_table.py
        startpage: $PRIVATEHTML/startpage.html
        startpage-source: $SYNCED/org/startpage.yaml
        startpage-style: $SYNCED/org/startpage.css
travel:
        travel-filename: $SYNCED/travel/travel.csv
        places-filename: $SYNCED/travel/places/places.csv
contacts:
        contacts-file: $SYNCED/org/contacts.csv
weather:
        weather-filename: $SYNCED/var/weather.csv
        sunlight-times-file: $SYNCED/var/sunlight-times.json
        weather-country: GB
        weather-city: Cambridge
archive:
        archive: $ARCHIVE
        backup-iso-format: backup-%s.iso
        backup-isos-directory: $ISOS/backups
        write-iso-to-dvd: true
        synced-snapshots: $SYNCEDSNAPSHOTS
        daily-backup-template: org-%s.tgz
        gpg-recipient: jcg.sturdy@gmail.com
        projects-dir: $HOME/open-projects/github.com
        projects-user: hillwithsmallfields
        monthly-backup-day: 1
        weekly-backup-day: Wednesday
        weekly-backup-template: Sync-%s.tgz
timetables:
        default-timetable: timetable.csv
        timetables-dir: $SYNCED/timetables
general:
        charts: $PRIVATEHTML/dashboard
        projects-dir: ~/open-projects/github.com
        projects-user: hillwithsmallfields
        reflections-dir: $SYNCED/texts/reflection
        org-directory: $ORG
        sync-directory: $SYNCED
noticeboard:
        chiming_times:
                Default: 06:30--22:00
                Saturday: 09:30--22:00
                Sunday: 05:30--22:00
        command_port: 10101
        camera:
                directory: /var/spool/camera
                duration: 180
        delays:
              activation: 2.0
              lamp: 0.01
              main_loop: 1.0
              motor: 0.01
        pir_log_file: /var/log/pir
house:
        expected_occupancy:
                 Friday:
                 - 06:00--08:30
                 - 17:30--23:30
                 Monday:
                 - 06:00--08:30
                 - 17:30--20:00
                 - 22:00--23:30
                 Saturday:
                 - 06:00--23:30
                 Sunday:
                 - 06:00--08:30
                 - 17:30--23:30
                 Thursday:
                 - 06:00--08:30
                 - 17:30--23:30
                 Tuesday:
                 - 06:00--08:30
                 - 17:30--23:30
                 Wednesday:
                 - 06:00--08:30
                 - 17:30--23:30
